### ISSUE TITLE
Display a warning if the destination folder has wrong ownership

### ISSUE THREAD

**Issue by LiamDawe** [lutris/lutris#1607]
Since nothing I've tried has worked, bug report hello!

Lutris 0.5 beta seems to be unable to install into a different drive, tried with StarCraft II.

Log: https://pastebin.com/j58svEH3

Newer Log: https://gist.github.com/LiamDawe/731770345fbc9e4a4b1eeaf8062c2035

**Comment by strycore** [comment]
Just to make sure, installing on the system drive works just fine?

**Comment by LiamDawe** [comment]
Yup, works fine in a folder in my home.

**Comment by strycore** [comment]
Ok, let's try something that is very close to my own setup. If you take a folder, make a symklink in your home and install the game there, do you still experience the problem?

I remember you saying that both drives where ext4 on Discord?

**Comment by LiamDawe** [comment]
Nope, Lutris says "NotADirectoryError(20, 'Not a directory')"

**Comment by strycore** [comment]
@LiamDawe I fixed the NotADirectoryError in a recent commit, which was an issue with how Wine prefix creation was handling symlinks, so not related to this issue. You can give it another try with the latest code.
Also, I tried installing Starcraft II in my /media/data3 drive and didn't notice any issue so it's weird that the install in the home directory goes fine for you but not on a different partition

**Comment by Zeioth** [comment]
@LiamDawe what's the format of your HD? Mine is NTFS and I can install games on it without any issue.

**Comment by smkuehnhold** [comment]
Having the same issue "Wine prefix creation is taking longer than expected...". No problems on my primary.

**Comment by LiamDawe** [comment]
Just confirming the bug is still present. I'm now on Manjaro KDE, much more up to date than the Ubuntu this was originally tested on, so it was not specific to Ubuntu.

Full log: https://gist.github.com/LiamDawe/ffd34b2ad57ba0d3beb58adfef101838

**Comment by strycore** [comment]
@LiamDawe can you also post the output of `lutris --submit-issue`? It will have some additional details about your drives

**Comment by LiamDawe** [comment]
Sorry for the long delay, emails get buried :(

Here you go dude: https://gist.github.com/LiamDawe/5137de1d000bc72f74b297628632b0d2

**Comment by strycore** [comment]
Your game drive is mounted on /media/games while the game tries to install in /mnt/games. There is definitely something wrong with your setup.
Can you go to ~/.config/lutris and search for references to "/mnt/games" there?

**Comment by LiamDawe** [comment]
That's probably left over from the Ubuntu locations, since I'm on Manjaro now it's under /media/ with the same problem so I don't think that's the issue.

Just to be sure, I've attempted to re-do the whole SC II install just now to get a fresh log file of the process on Manjaro: https://gist.github.com/LiamDawe/731770345fbc9e4a4b1eeaf8062c2035

Seems to be the same issue.

**Comment by strycore** [comment]
There, you have a permission issue in how your disks are mounted:
```/home/liam/.local/share/lutris/runners/wine/ge-protonified-nofshack-4.9-x86_64/bin/wine cmd.exe /c echo '%ProgramFiles%' returned empty string, error message "wine: '/media/games' is not owned by you, refusing to create a configuration directory there" ```

**Comment by LiamDawe** [comment]
_shocked pikachu gif_

You're right, did a quick:

> sudo chown -R $USER:$USER /media/games

Now it worked. God damn. Annoying since I could create folders and files on it anyway.

If there's a way to check for that, would be cool to see it in the error message :)

**Comment by strycore** [comment]
A message will now be displayed if the destination is not writable

**Comment by LiamDawe** [comment]
Brilliant! Thanks a lot dude.
