### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by sashaaaaaaaaa** [lutris/lutris#2469]
Running Debian 10, Lutris 0.5.3, can't launch game. Configure works at first but stops working after trying to launch game.

When trying to launch game:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/game_actions.py", line 150, in on_game_run
    self.application.launch(self.game)
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 343, in launch
    game.play()
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 286, in play
    self.configure_game(True)
  File "/usr/lib/python3/dist-packages/lutris/exceptions.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 308, in configure_game
    gameplay_info = self.runner.play()
  File "/usr/lib/python3/dist-packages/lutris/runners/linux.py", line 103, in play
    if not self.game_exe or not system.path_exists(self.game_exe):
  File "/usr/lib/python3/dist-packages/lutris/runners/linux.py", line 70, in game_exe
    exe_path = os.path.join(self.game_path, exe)
  File "/usr/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

When trying to configure game:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/game_actions.py", line 197, in on_edit_game_configuration
    EditGameConfigDialog(self.window, self.game)
  File "/usr/lib/python3/dist-packages/lutris/gui/config/edit_game.py", line 19, in __init__
    self.build_tabs("game")
  File "/usr/lib/python3/dist-packages/lutris/gui/config/common.py", line 68, in build_tabs
    self._build_game_tab()
  File "/usr/lib/python3/dist-packages/lutris/gui/config/common.py", line 322, in _build_game_tab
    self.game_box = GameBox(self.lutris_config, self.game)
  File "/usr/lib/python3/dist-packages/lutris/gui/config/boxes.py", line 615, in __init__
    self.generate_widgets("game")
  File "/usr/lib/python3/dist-packages/lutris/gui/config/boxes.py", line 90, in generate_widgets
    self.call_widget_generator(option, option_key, value, default)
  File "/usr/lib/python3/dist-packages/lutris/gui/config/boxes.py", line 183, in call_widget_generator
    self.generate_directory_chooser(option, value)
  File "/usr/lib/python3/dist-packages/lutris/gui/config/boxes.py", line 412, in generate_directory_chooser
    default_path = self.game.runner.working_dir
  File "/usr/lib/python3/dist-packages/lutris/runners/linux.py", line 91, in working_dir
    if self.game_exe:
  File "/usr/lib/python3/dist-packages/lutris/runners/linux.py", line 70, in game_exe
    exe_path = os.path.join(self.game_path, exe)
  File "/usr/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by tannisroot** [comment]
Can you try using master?

**Comment by strycore** [comment]
This is fixed in master

**Comment by Awo11** [comment]
hey @strycore , i have the same issue (installing league of legends, after going through with the steps, and choosing the language and server in the installer and continuing, i get this message). what is master and how do i use it because i am completely clueless. thx <3 :D

**Comment by tannisroot** [comment]
@Awo11 this is fixed in 0.5.4

**Comment by Awo11** [comment]
@tannisroot so i checked my version and it very well is 0.5.4
![Screenshot from 2019-12-11 21-44-52](https://user-images.githubusercontent.com/47328175/70646133-b86f6380-1c5f-11ea-97c1-3f96afe804d0.png)
and i still get the same error.

**Comment by tannisroot** [comment]
Can you give some clear reproduction steps on this? Like, which game you installed, on which distribution, and what do you do exactly when you encounter this error.

**Comment by Awo11** [comment]
alright. 
![Screenshot from 2019-12-11 21-51-30](https://user-images.githubusercontent.com/47328175/70646500-71ce3900-1c60-11ea-8caa-2b42c34366d2.png)
i installed lutris 2 days ago. i installed the game League of Legends to play with some friends from here https://lutris.net/games/league-of-legends/ 
it went well and i had fun. next day(today) i try and open it again and i get this error: https://github.com/lutris/lutris/issues/2501 
at this point in time i had decided to delete the game (not that smart of a decision)
i then was instructed to do as what's in https://github.com/lutris/lutris/issues/2504
i do, but then lutris won't start. i tried running it using multiple methods (thinking that my mouse was lagging or something)but to no avail, i returned everything to how it was and lutris went back to normally opening. made the change in the code again just to make sure i didn't do anything wrong and nope, i didnt do anything wrong.
so now, lutris is back to how it was installed
i redownload league of legends from the website provided above, the installer opens, goes through the first few steps, i choose what i desire from the settings (like language for eg.) and then i reach the step of choosing the server. i choose it and click next and then i get this error
![Screenshot from 2019-12-11 22-00-13](https://user-images.githubusercontent.com/47328175/70647130-b73f3600-1c61-11ea-83bf-49f13ec38706.png)

Last step in the installer before error:
![Screenshot from 2019-12-11 22-00-06](https://user-images.githubusercontent.com/47328175/70647151-c0c89e00-1c61-11ea-822c-f06ef4b29d48.png)

**Comment by Awo11** [comment]
sorry for making it that long

**Comment by tannisroot** [comment]
Can you post your log from running `lutris -d` and reproducing your issue here? just to make sure the error is the same.

**Comment by Awo11** [comment]
I used the command that you provided but i was unable to get an automatic file of the log so i manually copied all what was in the terminal:
INFO     2019-12-11 22:15:04,247 [application.do_command_line:225]:Running Lutris 0.5.4
INFO     2019-12-11 22:15:04,247 [startup.check_driver:55]:Using NVIDIA drivers 430.50 for x86_64
INFO     2019-12-11 22:15:04,247 [startup.check_driver:60]:GPU: GeForce 920M
INFO     2019-12-11 22:15:04,248 [startup.check_driver:79]:GPU: 10DE:1299 1025:100D using nvidia drivers
INFO     2019-12-11 22:15:04,248 [startup.check_driver:79]:GPU: 8086:1916 1025:100C using i915 drivers
INFO     2019-12-11 22:15:04,271 [startup.check_vulkan:132]:Vulkan is supported
INFO     2019-12-11 22:15:04,272 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
DEBUG    2019-12-11 22:15:04,719 [http.get:65]:GET https://lutris.net/api/runtime
INFO     2019-12-11 22:15:04,719 [lutriswindow.toggle_connection:590]:Connected to lutris.net as motaz910
DEBUG    2019-12-11 22:15:04,724 [http.get:65]:GET https://lutris.net/api/games/library/motaz910
INFO     2019-12-11 22:15:06,033 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
2019-12-11 22:15:21,309: Running Lutris 0.5.4
2019-12-11 22:15:21,310: Using NVIDIA drivers 430.50 for x86_64
2019-12-11 22:15:21,310: GPU: GeForce 920M
2019-12-11 22:15:21,310: GPU: 10DE:1299 1025:100D using nvidia drivers
2019-12-11 22:15:21,310: GPU: 8086:1916 1025:100C using i915 drivers
2019-12-11 22:15:21,334: Vulkan is supported
2019-12-11 22:15:21,338: Fetching installer https://lutris.net/api/installers/league-of-legends-vsyscall32-override-
2019-12-11 22:15:21,339: GET https://lutris.net/api/installers/league-of-legends-vsyscall32-override-
2019-12-11 22:15:30,967: Required runners: [<lutris.runners.wine.wine object at 0x7f0fa074ff98>]
2019-12-11 22:15:30,986: Downloading file 1 of 1
2019-12-11 22:15:30,989: Downloading [lol_installer]: https://riotgamespatcher-a.akamaihd.net/releases/live/installer/deploy/League%20of%20Legends%20installer%20NA.exe to /home/awo11/.cache/lutris/installer/league-of-legends/lol_installer/League%20of%20Legends%20installer%20NA.exe
2019-12-11 22:15:30,998: Downloading https://riotgamespatcher-a.akamaihd.net/releases/live/installer/deploy/League%20of%20Legends%20installer%20NA.exe to /home/awo11/.cache/lutris/installer/league-of-legends/lol_installer/League%20of%20Legends%20installer%20NA.exe
2019-12-11 22:15:31,002: Starting download of:
 https://riotgamespatcher-a.akamaihd.net/releases/live/installer/deploy/League%20of%20Legends%20installer%20NA.exe
2019-12-11 22:15:54,028: Finished downloading https://riotgamespatcher-a.akamaihd.net/releases/live/installer/deploy/League%20of%20Legends%20installer%20NA.exe
2019-12-11 22:15:54,059: Installer command: {'input_menu': {'options': [{'cs_CZ': 'Čeština'}, {'en_AU': 'English AUS'}, {'en_GB': 'English U.K.'}, {'en_US': 'English U.S.'}, {'fr_FR': 'Français'}, {'de_DE': 'Deutsch'}, {'es_ES': 'Español'}, {'es_MX': 'Español Mexicano'}, {'it_IT': 'Italiano'}, {'ja_JP': '日本語'}, {'hu_HU': 'Magyar'}, {'pl_PL': 'Polski'}, {'pt_BR': 'Português do Brasil'}, {'ro_RO': 'Romanian'}, {'ru_RU': 'русский'}, {'tr_TR': 'Türkçe'}], 'preselect': 'en_US', 'id': 'LOCALE'}}
2019-12-11 22:16:11,758: Installer command: {'input_menu': {'options': [{'BR': 'Brazil'}, {'EUNE': 'Europe Nordic & East'}, {'EUW': 'Europe West'}, {'LAN': 'Latin America North'}, {'LAS': 'Latin America South'}, {'NA': 'North America'}, {'OCE': 'Oceania'}, {'RU': 'Russia'}, {'TR': 'Turkey'}, {'JP': 'Japan'}, {'SEA': 'South East Asia'}], 'preselect': 'NA', 'id': 'REGION'}}

(lutris:4257): Gtk-CRITICAL **: 22:16:14.720: gtk_tree_model_get_column_type: assertion 'GTK_IS_TREE_MODEL (tree_model)' failed

(lutris:4257): Gtk-CRITICAL **: 22:16:14.720: gtk_combo_box_get_active_id: assertion 'gtk_tree_model_get_column_type (model, column) == G_TYPE_STRING' failed
2019-12-11 22:16:14,724: Installer command: {'task': {'prefix': '$GAMEDIR', 'arch': 'win32', 'name': 'create_prefix'}}
2019-12-11 22:16:14,729: Creating a win32 prefix in /home/awo11/Games/league-of-legends
2019-12-11 22:16:14,729: Executing /home/awo11/.local/share/lutris/runners/wine/lutris-lol-4.20-x86_64/bin/wineboot
2019-12-11 22:16:14,730: WINEARCH=win32 WINEPREFIX=/home/awo11/Games/league-of-legends WINEDLLOVERRIDES=
2019-12-11 22:16:15,920: win32 Prefix created in /home/awo11/Games/league-of-legends
2019-12-11 22:16:15,952: Error while completing task <bound method CommandsMixin.task of <lutris.installer.interpreter.ScriptInterpreter object at 0x7f0fa071ceb8>>: expected str, bytes or os.PathLike object, not NoneType
<class 'TypeError'> expected str, bytes or os.PathLike object, not NoneType
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 407, in task
    thread = task(**data)
  File "/usr/lib/python3/dist-packages/lutris/runners/commands/wine.py", line 150, in create_prefix
    prefix_manager.setup_defaults()
  File "/usr/lib/python3/dist-packages/lutris/util/wine/prefix.py", line 27, in setup_defaults
    self.desktop_integration()
  File "/usr/lib/python3/dist-packages/lutris/util/wine/prefix.py", line 127, in desktop_integration
    src_path = os.path.join(desktop_dir, item)
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
Gtk-Message: 22:16:23.975: GtkDialog mapped without a transient parent. This is discouraged.
2019-12-11 22:16:26,472: Cancelling installation of League of Legends
2019-12-11 22:16:26,486: Killing all wine processes: ['/home/awo11/.local/share/lutris/runners/wine/lutris-lol-4.20-x86_64/bin/wineserver', '-k']
2019-12-11 22:16:26,487: 	Wine prefix: /home/awo11/Games/league-of-legends
2019-12-11 22:16:26,487: 	Wine arch: win64
2019-12-11 22:16:26,507: Waiting for wine processes to terminate
2019-12-11 22:16:26,509: Done waiting.
2019-12-11 22:16:26,510: Removing folder /home/awo11/.cache/lutris/installer/league-of-legends

(lutris:4257): Gtk-CRITICAL **: 22:17:37.715: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.722: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.726: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.728: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.733: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.736: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.740: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.744: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.748: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.752: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.756: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.760: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.764: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.768: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.769: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.773: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.777: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.781: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.785: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.789: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.793: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.798: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.802: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.806: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.810: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.814: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.818: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.823: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.827: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.833: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.837: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.839: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.844: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.850: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.854: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

(lutris:4257): Gtk-CRITICAL **: 22:17:37.865: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed
2019-12-11 22:17:47,898: Retrieving video modes from XrandR
2019-12-11 22:19:58,998: Failed to open URI irc://irc.freenode.org:6667/lutris: g-io-error-quark: The specified location is not supported (15)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/utils.py", line 46, in open_uri
    Gtk.show_uri(None, uri, Gdk.CURRENT_TIME)
GLib.GError: g-io-error-quark: The specified location is not supported (15)
2019-12-11 22:20:05,388: GET https://lutris.net/api/runners/wine

**Comment by strycore** [comment]
I don't see how this happens so I'm raising another error, send the details of this one in a new issue and I can work from there.
