### ISSUE TITLE
Vice does not find game

### ISSUE THREAD

**Issue by dnop** [lutris/lutris#377]
When I start a C64 game from lutris clint, the vice window opens, but the C64 console says "File not found".
Furthermore I am not able to type anything into the C64 shell. The window does not accept any key press.

**Comment by strycore** [comment]
what type of file extension does the game have? The supported formats should be  X64, D64, G64, P64, D67, D71, D81, D80, D82, D1M, D2M, D4M, T46, P00 and CRT but it's possible that we are not passing the correct arguments for some of them.

**Comment by telanus** [comment]
Hi. tested it and got this on the terminal:

Traceback (most recent call last):
  File "/home/batapete/src/lutris/lutris/gui/lutriswindow.py", line 538, in on_game_run
    self.running_game.play()
  File "/home/batapete/src/lutris/lutris/game.py", line 161, in play
    self.do_play(True)
  File "/home/batapete/src/lutris/lutris/game.py", line 169, in do_play
    gameplay_info = self.runner.play()
  File "/home/batapete/src/lutris/lutris/runners/vice.py", line 109, in play
    if rom.endswith('.crt'):
AttributeError: 'NoneType' object has no attribute 'endswith'

Used this one:
[Cybernoid II.p00.zip](https://github.com/lutris/lutris/files/507052/Cybernoid.II.p00.zip)

**Comment by dnop** [comment]
The file extensions is .d64.
I attached a screenshot and the console log
![bildschirmfoto1](https://cloud.githubusercontent.com/assets/22599894/19064229/33519b2a-8a0c-11e6-9030-712d0217c8c8.png)

**Comment by dnop** [comment]
Sorry, console log upload didn't work. Here it is:
*** VICE Version 2.4 ***
OS compiled for: Linux
GUI compiled for: NATIVE
CPU compiled for: AMD64/x86_64
Compiler used: GCC-4.8.4
Current OS: *nix
Current CPU: Intel Pentium Pro/II/III/Celeron/Core/Core 2/Atom
 
Welcome to x64, the free portable C64 Emulator.
 
Current VICE team members:
D. Lem, A. Matthies, M. Pottendorfer, S. Trikaliotis, M. van den Heuvel,
C. Vogelgsang, F. Gennari, D. Kahlin, A. Lankila, Groepaz, I. Korb,
E. Smith, O. Seibert, M. Sutton, U. Schulz, S. Haubenthal, T. Giesel,
K. Zsolt.
 
This is free software with ABSOLUTELY NO WARRANTY.
See the "About VICE" command for more info.
 
X11: Found 24bit/TrueColor visual.
X11: Using private colormap.
XRandR: XRandR reports current display: 1920x1080@50
Loading system file `/home/desktop/.local/share/lutris/runners/vice/lib64/vice/C64/kernal'.
C64MEM: Kernal rev #3.
Loading system file `/home/desktop/.local/share/lutris/runners/vice/lib64/vice/C64/basic'.
Loading system file `/home/desktop/.local/share/lutris/runners/vice/lib64/vice/C64/chargen'.
MPS-803: Error - Could not load MPS-803 charset 'mps803'.
MPS-803: Error - Cannot load palette file `mps803.vpl'.
NL10: Error - Could not load NL-10 ROM file 'nl10-cbm'.
IECDriveROM: Error - 1541 ROM image not found.  Hardware-level 1541 emulation is not available.
IECDriveROM: Error - 1541-II ROM image not found.  Hardware-level 1541-II emulation is not available.
IECDriveROM: Error - 1570 ROM image not found.  Hardware-level 1570 emulation is not available.
IECDriveROM: Error - 1571 ROM image not found.  Hardware-level 1571 emulation is not available.
IECDriveROM: Error - 1581 ROM image not found.  Hardware-level 1581 emulation is not available.
IECDriveROM: Error - 2000 ROM image not found.  Hardware-level 2000 emulation is not available.
IECDriveROM: Error - 4000 ROM image not found.  Hardware-level 4000 emulation is not available.
IEEEDriveROM: Error - 2031 ROM image not found.  Hardware-level 2031 emulation is not available.
IEEEDriveROM: Error - 2040 ROM image not found.  Hardware-level 2040 emulation is not available.
IEEEDriveROM: Error - 3040 ROM image not found.  Hardware-level 3040 emulation is not available.
IEEEDriveROM: Error - 4040 ROM image not found.  Hardware-level 4040 emulation is not available.
IEEEDriveROM: Error - 1001 ROM image not found.  Hardware-level 1001/8050/8250 emulation is not available.
Drive: Finished loading ROM images.
Warning: Missing charsets in String to FontSet conversion
Warning: Missing charsets in String to FontSet conversion
Warning: Missing charsets in String to FontSet conversion
X11Video: Successfully initialized using XVideo (768x544 UYVY), using shared memory.
Sound: Available sound devices: pulse alsa uss dummy fs dump wav voc iff aiff soundmovie
Keyboard: Error - Cannot load keymap `x11_sym.vkm'.
Joystick: Linux joystick interface initialization...
Joystick: /dev/input/js0 is Code Mercenaries JoyWarrior Gamepad 32
Joystick: Built in driver version: 2.1.0
Joystick: Kernel driver version  : 2.1.0
Joystick: Warning - Cannot open joystick device `/dev/input/js1'.
Joystick: Warning - Cannot open joystick device `/dev/input/js2'.
Joystick: Warning - Cannot open joystick device `/dev/input/js3'.
Joystick: Warning - Cannot open joystick device `/dev/input/js4'.
Joystick: Warning - Cannot open joystick device `/dev/input/js5'.
AUTOSTART: Autodetecting image type of `/home/desktop/Games/C64/GianaSisters/The_Great_Giana_Sisters_(REM).d64'.
AUTOSTART: Attached file `/home/desktop/Games/C64/GianaSisters/The_Great_Giana_Sisters_(REM).d64' as a disk image.
AUTOSTART: Resetting the machine to autostart '*'
AUTOSTART: Turning Warp mode on
AUTOSTART: `/home/desktop/Games/C64/GianaSisters/The_Great_Giana_Sisters_(REM).d64' recognized as disk image.
Main CPU: starting at ($FFFC).
Main CPU: RESET.
Sound: Opened device `pulse', speed 44100Hz, fragment size 11ms, buffer size 104ms
reSID: MOS6581, filter on, sampling rate 44100Hz - fast
AUTOSTART: Loading program '*'
AUTOSTART: NO Searching for ...
AUTOSTART: Turning Warp mode off
AUTOSTART: Error - Turned off.

**Comment by dnop** [comment]
I tried to invoke vice directly:
cd ~/.local/share/lutris/runners/vice/bin
x64 --autostart <ImageName>
That worked fine.
What is the command line invoked by lutris to start vice ?

**Comment by strycore** [comment]
@dnop the command line used to launch Vice is something like:

`"/home/strider/.local/share/lutris/runners/vice/bin/x64" "-chdir" "/home/strider/.local/share/lutris/runners/vice/lib64/vice/C64" "-fullscreen" "-joydev1" "5" "-joydev2" "6" "/home/strider/Desktop/Cybernoid II.p00"`

It's visible from the command line if you run lutris -d

I've made a few changes to the runner, first there are checks that an existing ROM file is provided before running the game. Then I also fixed the fullscreen argument and added an argument for the 2nd joystick and finally I added a post install task that will copy the contents of vice/lib64/vice to ~/.vice (this will fix the keyboard not typing anything)

Is there anything missing? Also, does anyone know how to get rid of the CRT controls on the bottom of the screen and get true fullscreen?

**Comment by strycore** [comment]
btw, to get the vice to install properly (install the files in ~/.vice), you need to delete the folder in ~/.local/share and re-download the runner (or just copy the files manually).

**Comment by strycore** [comment]
With a brand new Vice runner and fixed command line options, is it ok to close this now?

**Comment by telanus** [comment]
it still don't run here :(

doesn't leave anything in the game's logs according to lutris, but this is outputted on the terminal: http://pastebin.com/ug1C3LXd

**Comment by dnop** [comment]
I removed the whole runner directory (rm -rf ~/.local/share/lutris/runners/vice.
Then I installed vice again from the runner manager window.
The behavior is still the same.

**Comment by telanus** [comment]
I've tried it now from the commandline:
`LD_LIBRARY_PATH=/home/user001/.local/share/lutris/runtime/lib64 /home/user001/.local/share/lutris/runners/vice/bin/x64 -chdir "/Games/Romz/MESS/Software/c64" -VICIIdsize "/Games/Romz/MESS/Software/c64/cosmos.prg"`

it exits with:
`Illegal instruction (core dumped)`

**Comment by strycore** [comment]
Also ran the same thing and no issue here:
`LD_LIBRARY_PATH=/home/strider/.local/share/lutris/runtime/lib64 /home/strider/.local/share/lutris/runners/vice/bin/x64 -chdir "/home/strider/Games/commodore/c64" -VICIIdsize /home/strider/Games/commodore/c64/Cosmos\ \#01\ \(19xx\)\(Cosmos\).prg`

So, I guess this is an issue with the runtime or some other kind of library conflict.
Can you send the output of 

`ldd ~/.local/share/lutris/runners/vice/bin/x64`

and

`strace ~/.local/share/lutris/runners/vice/bin/x64`

(Both with the Lutris runtime loaded)

**Comment by telanus** [comment]
output:
ldd: http://pastebin.com/VJgztWaf
strace: http://pastebin.com/Fn6NsKwG <== what is left on the terminal

**Comment by strycore** [comment]
Can't really figure out what's going on here… 

Have you reinstalled everything from the lutris (including the contents of ~/.vice)?

**Comment by telanus** [comment]
yes reinstalled twice

**Comment by strycore** [comment]
I had a similar crash on my Debian 8 VM (but the strace exited with SIGSEGV instead). I add a renderer option to the runner and now Vice doesn't crash but I get a black window (except when I move the Vice window then I can see the output for a fraction of a second). That may just be the results of running Vice in a VM… Can you test with the software renderer and see if that helps?

**Comment by strycore** [comment]
Damn, that is a strange one… Can you remind me what distro you're running? I probably have a VM I can test that on.

**Comment by telanus** [comment]
I'm running Ubuntu 16.04.01 with nVidia gpu. It's the only runner that don't work ( of those I tried)

**Comment by strycore** [comment]
that is even stranger because I run the exact same thing :(

**Comment by beansmyname** [comment]
This [gist](https://gist.github.com/beansmyname/9801e0714785f32169d7ae9bf4d94ef0) contains a gdb backtrace, the output of ldd and strace output when attempting to launch a game using the x64 VICE runner.

Notes:
I was in the lutris/runners/vice dir when these were run. I had copied the Night Mission Pinball (1982)(Sublogic).d64 file to that directory as nmp.d64 as an attempt to shorten the command line. The illegal instruction occurs with or without options after x64.

**Comment by strycore** [comment]
can you try creating the most minimal runtime that would be able to launch the emulator and see if the crash still happens?

I think that you will need libgif.so.4 from the runtime/lib64 folder and maybe a couple other ones depending on what you have installed (this version of libgif isn't available in current distros, it's from Ubuntu 14.04 which is why you'll need to get it from the runtime)

**Comment by beansmyname** [comment]
created a mini-runtime folder and only had to put libreadline.so.6 and libgif.so.4 in it to trigger the crash.

ldd output:
```
linux-vdso.so.1 (0x00007ffd11fc3000)
libpulse-simple.so.0 => /usr/lib/libpulse-simple.so.0 (0x00007fb00edc4000)
libpulse.so.0 => /usr/lib/libpulse.so.0 (0x00007fb00eb73000)
libasound.so.2 => /usr/lib/libasound.so.2 (0x00007fb00e868000)
libjpeg.so.8 => /usr/lib/libjpeg.so.8 (0x00007fb00e5fe000)
libgif.so.4 => /home/robean/.local/share/lutris/mini-runtime/libgif.so.4 (0x00007fb00e3f5000)
libpng12.so.0 => /usr/lib/libpng12.so.0 (0x00007fb00e1cc000)
libz.so.1 => /usr/lib/libz.so.1 (0x00007fb00dfb6000)
libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fb00ddb2000)
libreadline.so.6 => /home/robean/.local/share/lutris/mini-runtime/libreadline.so.6 (0x00007fb00db6c000)
libieee1284.so.3 => /usr/lib/libieee1284.so.3 (0x00007fb00d960000)
libFLAC.so.8 => /usr/lib/libFLAC.so.8 (0x00007fb00d6ea000)
libvorbisenc.so.2 => /usr/lib/libvorbisenc.so.2 (0x00007fb00d437000)
libvorbisfile.so.3 => /usr/lib/libvorbisfile.so.3 (0x00007fb00d22e000)
libvorbis.so.0 => /usr/lib/libvorbis.so.0 (0x00007fb00d001000)
libogg.so.0 => /usr/lib/libogg.so.0 (0x00007fb00cdfa000)
libSDL2-2.0.so.0 => /usr/lib/libSDL2-2.0.so.0 (0x00007fb00cae0000)
libmpg123.so.0 => /usr/lib/libmpg123.so.0 (0x00007fb00c881000)
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fb00c4f9000)
libm.so.6 => /usr/lib/libm.so.6 (0x00007fb00c1f5000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007fb00be57000)
libpulsecommon-9.0.so => /usr/lib/pulseaudio/libpulsecommon-9.0.so (0x00007fb00bbd4000)
libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fb00b9b7000)
libjson-c.so.2 => /usr/lib/libjson-c.so.2 (0x00007fb00b7ac000)
libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x00007fb00b55c000)
librt.so.1 => /usr/lib/librt.so.1 (0x00007fb00b354000)
/lib64/ld-linux-x86-64.so.2 (0x00007fb00efc9000)
libtinfo.so.5 => /usr/lib/libtinfo.so.5 (0x00007fb00b0fb000)
libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fb00aee4000)
libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007fb00acbb000)
libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007fb00f10d000)
libsndfile.so.1 => /usr/lib/libsndfile.so.1 (0x00007fb00aa43000)
libasyncns.so.0 => /usr/lib/libasyncns.so.0 (0x00007fb00a83d000)
libXau.so.6 => /usr/lib/libXau.so.6 (0x00007fb00a639000)
libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007fb00a433000)
libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007fb00a21c000)
libcap.so.2 => /usr/lib/libcap.so.2 (0x00007fb00a018000)
liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007fb009df2000)
liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007fb009be0000)
libgcrypt.so.20 => /usr/lib/libgcrypt.so.20 (0x00007fb0098d1000)
libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007fb0096bd000)
```
Same illegal hardware instruction and backtrace looks the same. If you need anything else, let me know.

**Comment by strycore** [comment]
I've added a script to get more info on specific configs, it's not yet shipped but it's on Github here: https://raw.githubusercontent.com/lutris/lutris/master/share/lutris/bin/desktop_info.sh

Can you send me back the results?

**Comment by beansmyname** [comment]
```
Desktop Info for Lutris

Environment variables:
DESKTOP_SESSION=
GDMSESSION=
SHELL=/bin/zsh

Distribution:
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
Linux hellbound 4.8.8-2-ARCH #1 SMP PREEMPT Thu Nov 17 14:51:03 CET 2016 x86_64 GNU/Linux

Running desktop processes:
32 kdevtmpfs

OpenGL info:
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Desktop 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 13.0.1
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 13.0.1
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 13.0.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

RAM info:
              total        used        free      shared  buff/cache   available
Mem:           6.8G        2.2G        125M        292M        4.4G        4.0G
Swap:          8.0G        133M        7.9G

CPU info:
model name	: Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz

Wine info:
Wine installed system wide: /usr/bin/wine
Version: wine-1.9.22 (Staging)
----------------------------------------------------------------------------
```
I'm using the i3 window manager and use startx at the console.

**Comment by strycore** [comment]
I would say it's related to Mesa but @telanus has the same issue on a Nvidia GPU. 
I don't have a laptop anymore so I can't test it on an Intel GPU.

**Comment by beansmyname** [comment]
For what it's worth, this doesn't happen with my installed version of vice
(2.4) if the SDL options aren't passed. Is there some way to override those
options and use the system installed vice?

**Comment by telanus** [comment]
here's Mine:
```

Desktop Info for Lutris


Environment variables:
DESKTOP_SESSION=mate
GDMSESSION=mate
SHELL=/bin/bash


Distribution:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
Linux Dragonite 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux


Running desktop processes:
16 kdevtmpfs
1391 mate-session
1778 gnome-keyring-d
1782 mate-settings-d
1786 mate-panel
1864 mate-maximus
1866 mate-volume-con
1873 polkit-mate-aut
3298 mate-terminal
3303 gnome-pty-helpe


OpenGL info:
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GT 240/PCIe/SSE2
OpenGL core profile version string: 3.3.0 NVIDIA 340.98
OpenGL core profile shading language version string: 3.30 NVIDIA via Cg compiler
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.3.0 NVIDIA 340.98
OpenGL shading language version string: 3.30 NVIDIA via Cg compiler
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 NVIDIA 340.98 340.98
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.00
OpenGL ES profile extensions:


RAM info:
              total        used        free      shared  buff/cache   available
Mem:           2.9G        1.1G        917M         35M        975M        1.6G
Swap:          9.2G          0B        9.2G


CPU info:
model name	: Pentium(R) Dual-Core  CPU      E5300  @ 2.60GHz


Wine info:
Wine installed system wide: /usr/bin/wine
Version: wine-1.9.23
```

**Comment by strycore** [comment]
I've uploaded a new Vice runner, it's build against the latest SVN branch on Ubuntu 16.04 instead of Ubuntu 14.04. It's been made the default version so if you delete your vice folder and redownload it you'll get that version.

Direct link: https://lutris.net/files/runners/vice-r32372-x86_64.tar.gz

**Comment by telanus** [comment]
I tried the new runner, and still the same result :sob: 

did a gdb and bt and my results are the same as @beansmyname one of 5 days ago

**Comment by strycore** [comment]
Ok, then we have to go deeper…
If you build  Vice with this script on your machine, first does the script complete and then, if you use that build as the Lutris runner, do you still have the crash?

https://github.com/lutris/buildbot/blob/master/runners/vice/build.sh

**Comment by beansmyname** [comment]
Not having the ../../lib dirs, I commented out those lines and skipped
the build deps (made sure that I had time installed) since I'm on arch
and that would definitely have failed. Vice built fine, removed the
vice runner manually and untarred the freshly built version and now
I'm getting this from ldd:

```
./bin/x64: /home/robean/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libpci.so.3:
version `LIBPCI_3.5' not found (required by ./bin/x64)
linux-vdso.so.1 (0x00007ffc0ede6000)
libpulse-simple.so.0 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libpulse-simple.so.0
(0x00007f70245f0000)
libpulse.so.0 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libpulse.so.0
(0x00007f70243a8000)
libasound.so.2 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libasound.so.2
(0x00007f70240ad000)
libjpeg.so.8 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libjpeg.so.8
(0x00007f7023e5d000)
libgif.so.7 => /usr/lib/libgif.so.7 (0x00007f7023c53000)
libpng16.so.16 =>
/home/robean/.local/share/lutris/runtime/lib64/libpng16.so.16
(0x00007f7023a20000)
libz.so.1 => /home/robean/.local/share/lutris/runtime/lib64/libz.so.1
(0x00007f7023807000)
libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f7023603000)
libnet.so.1 => /usr/lib/libnet.so.1 (0x00007f70233e9000)
libbsd.so.0 => /usr/lib/libbsd.so.0 (0x00007f70231d3000)
libnsl.so.1 => /usr/lib/libnsl.so.1 (0x00007f7022fbb000)
libreadline.so.7 => /usr/lib/libreadline.so.7 (0x00007f7022d6d000)
libieee1284.so.3 => /usr/lib/libieee1284.so.3 (0x00007f7022b61000)
libpci.so.3 => /home/robean/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libpci.so.3
(0x00007f7022955000)
libFLAC.so.8 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libFLAC.so.8
(0x00007f702270b000)
libvorbisenc.so.2 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libvorbisenc.so.2
(0x00007f702223c000)
libvorbisfile.so.3 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libvorbisfile.so.3
(0x00007f7022034000)
libvorbis.so.0 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libvorbis.so.0
(0x00007f7021e08000)
libogg.so.0 => /home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libogg.so.0
(0x00007f7021c01000)
libSDL2-2.0.so.0 =>
/home/robean/.local/share/lutris/runtime/lib64/libSDL2-2.0.so.0
(0x00007f70218fa000)
libportaudio.so.2 => /usr/lib/libportaudio.so.2 (0x00007f70216ca000)
libmpg123.so.0 =>
/home/robean/.local/share/lutris/runtime/lib64/libmpg123.so.0
(0x00007f7021473000)
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f70210eb000)
libm.so.6 => /usr/lib/libm.so.6 (0x00007f7020de7000)
libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f7020bd0000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007f7020832000)
libpulsecommon-1.1.so =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libpulsecommon-1.1.so
(0x00007f70205d4000)
libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f70203b7000)
libjson.so.0 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libjson.so.0
(0x00007f70201af000)
libdbus-1.so.3 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3
(0x00007f701ff6b000)
librt.so.1 => /usr/lib/librt.so.1 (0x00007f701fd63000)
/lib64/ld-linux-x86-64.so.2 (0x00007f70247f4000)
libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x00007f701faf7000)
libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f701f8e0000)
libjack.so.0 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libjack.so.0
(0x00007f701f69c000)
libxcb.so.1 => /home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libxcb.so.1
(0x00007f701f47d000)
libwrap.so.0 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libwrap.so.0
(0x00007f701f274000)
libsndfile.so.1 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libsndfile.so.1
(0x00007f701f00e000)
libasyncns.so.0 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libasyncns.so.0
(0x00007f701ee08000)
libXau.so.6 => /home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libXau.so.6
(0x00007f701ec05000)
libXdmcp.so.6 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libXdmcp.so.6
(0x00007f701e9ff000)
```

**Comment by beansmyname** [comment]
Not having the ../../lib dirs, I commented out those lines and skipped
the build deps (made sure that I had time installed) since I'm on arch
and that would definitely have failed. Vice built fine, removed the
vice runner manually and untarred the freshly built version and now
I'm getting this from ldd:

```
./bin/x64: /home/robean/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libpci.so.3:
version `LIBPCI_3.5' not found (required by ./bin/x64)
linux-vdso.so.1 (0x00007ffc0ede6000)
libpulse-simple.so.0 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libpulse-simple.so.0
(0x00007f70245f0000)
libpulse.so.0 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libpulse.so.0
(0x00007f70243a8000)
libasound.so.2 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libasound.so.2
(0x00007f70240ad000)
libjpeg.so.8 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libjpeg.so.8
(0x00007f7023e5d000)
libgif.so.7 => /usr/lib/libgif.so.7 (0x00007f7023c53000)
libpng16.so.16 =>
/home/robean/.local/share/lutris/runtime/lib64/libpng16.so.16
(0x00007f7023a20000)
libz.so.1 => /home/robean/.local/share/lutris/runtime/lib64/libz.so.1
(0x00007f7023807000)
libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f7023603000)
libnet.so.1 => /usr/lib/libnet.so.1 (0x00007f70233e9000)
libbsd.so.0 => /usr/lib/libbsd.so.0 (0x00007f70231d3000)
libnsl.so.1 => /usr/lib/libnsl.so.1 (0x00007f7022fbb000)
libreadline.so.7 => /usr/lib/libreadline.so.7 (0x00007f7022d6d000)
libieee1284.so.3 => /usr/lib/libieee1284.so.3 (0x00007f7022b61000)
libpci.so.3 => /home/robean/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libpci.so.3
(0x00007f7022955000)
libFLAC.so.8 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libFLAC.so.8
(0x00007f702270b000)
libvorbisenc.so.2 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libvorbisenc.so.2
(0x00007f702223c000)
libvorbisfile.so.3 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libvorbisfile.so.3
(0x00007f7022034000)
libvorbis.so.0 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libvorbis.so.0
(0x00007f7021e08000)
libogg.so.0 => /home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libogg.so.0
(0x00007f7021c01000)
libSDL2-2.0.so.0 =>
/home/robean/.local/share/lutris/runtime/lib64/libSDL2-2.0.so.0
(0x00007f70218fa000)
libportaudio.so.2 => /usr/lib/libportaudio.so.2 (0x00007f70216ca000)
libmpg123.so.0 =>
/home/robean/.local/share/lutris/runtime/lib64/libmpg123.so.0
(0x00007f7021473000)
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f70210eb000)
libm.so.6 => /usr/lib/libm.so.6 (0x00007f7020de7000)
libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f7020bd0000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007f7020832000)
libpulsecommon-1.1.so =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libpulsecommon-1.1.so
(0x00007f70205d4000)
libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f70203b7000)
libjson.so.0 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libjson.so.0
(0x00007f70201af000)
libdbus-1.so.3 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3
(0x00007f701ff6b000)
librt.so.1 => /usr/lib/librt.so.1 (0x00007f701fd63000)
/lib64/ld-linux-x86-64.so.2 (0x00007f70247f4000)
libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x00007f701faf7000)
libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f701f8e0000)
libjack.so.0 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libjack.so.0
(0x00007f701f69c000)
libxcb.so.1 => /home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libxcb.so.1
(0x00007f701f47d000)
libwrap.so.0 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libwrap.so.0
(0x00007f701f274000)
libsndfile.so.1 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libsndfile.so.1
(0x00007f701f00e000)
libasyncns.so.0 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libasyncns.so.0
(0x00007f701ee08000)
libXau.so.6 => /home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libXau.so.6
(0x00007f701ec05000)
libXdmcp.so.6 =>
/home/robean/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libXdmcp.so.6
(0x00007f701e9ff000)
```

**Comment by beansmyname** [comment]
On a lark, I copied libpci.so.3 from my system to the lutris runtime lib64 folder and now Vice works as expected with the SDL switches in place.

**Comment by telanus** [comment]
@strycore compiled without any problems, and it works when replace the one I downloaded yesterday with the one I compiled.

**Comment by strycore** [comment]
I built a new version here: https://lutris.net/files/runners/vice-r34400-x86_64.tar.gz can  anyone test it and tell me if it's better?

**Comment by telanus** [comment]
Not working comes up with illegal instruction :(

[ldd](https://pastebin.com/jRHe50R9)

[strace](https://pastebin.com/fK263fP1)
