### ISSUE TITLE
Can't install anything via Lutris

### ISSUE THREAD

**Issue by proudhon** [lutris/lutris#4532]
Hello,

Since today i can't install anything via Lutris.
This also occurs for any game previously installed (uninstalled them on purpose and tried to re-install them)
I would add that this occurred after switching to wine-ge and reverting to wine or wine-staging (tried them both).
I followed all basic procedures (reinstalled all dependencies, deleted ~/.wine and ~/Games, reinstalled all runners).

Output and screenshot:

````
lutris-wrapper: /home/gec/.local/share/lutris/runtime/winetricks/winetricks
Started initial process 6371 from /home/gec/.local/share/lutris/runtime/winetricks/winetricks --unattended arial
Start monitoring process.
Executing mkdir -p /home/gec/Games
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
WINEPREFIX INFO:
Drive C: total 0
drwxr-xr-x 1 gec gec  72 30 set 19.38 .
drwxr-xr-x 1 gec gec 154 30 set 19.43 ..
drwxr-xr-x 1 gec gec  18 30 set 19.38 ProgramData
drwxr-xr-x 1 gec gec 118 30 set 19.38 Program Files
drwxr-xr-x 1 gec gec  18 30 set 19.38 users
drwxr-xr-x 1 gec gec 342 30 set 19.38 windows

Registry info:
/home/gec/Games/battlenet/system.reg:#arch=win64
/home/gec/Games/battlenet/userdef.reg:#arch=win64
/home/gec/Games/battlenet/user.reg:#arch=win64
------------------------------------------------------
------------------------------------------------------
warning: /home/gec/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "" 
------------------------------------------------------
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
````

![256](https://user-images.githubusercontent.com/94576412/193329093-830e02ae-7c57-40fb-86c4-219d7d9ac4a1.png)

**Comment by l0drex** [comment]
Same for me. Tried to log in to Ubisoft connect, got into the installation of the launcher and after a while I see this error. Also happens with epic games and origin. Lutris just hangs and I have to kill it from the system monitor.

My logs are [here](https://pastebin.com/UBQ8EN1d)

**Comment by proudhon** [comment]
Update and somewhat good news:
The issue seems to be user-related (at least in my case)
I created a fresh user and ran installation scripts via GUI.
Everything works as expected.
Still i can't get anything to install on my main user, even after cleaning .config/lutris and everything under .local/share/lutris and .local/share/winetricks. I also checked my shell rc files for conflicting env variable and set my default shell to bash but nothing changed.
Does anyone have a list of files/env variables to purge for having a clean strarting point?

**Comment by danieljohnson2** [comment]
You also want to delete ~/.cache/lutris, I think.

**Comment by proudhon** [comment]
> You also want to delete ~/.cache/lutris, I think.

Just tried, same behavior.

**Comment by l0drex** [comment]
Creating a new user didn't work for me. 

I also tried switching to Wayland, running from the master branch, disabling `prefer system libraries` and disabling the Lutris runtime as other issues suggested, but none of this solved the issue.

**Comment by l0drex** [comment]
Ok, so I tried to debug this and put some breakpoints in `runners/commands/wine.py` and `command.py` and it worked. So it is probably some kind of race condition?

**Comment by proudhon** [comment]
Ran installation on terminal with debugging enabled,
log: https://pastebin.com/TwiKRdQk

**Comment by proudhon** [comment]
Now, I removed the Arial installation task from the script, installation proceeds and fails with exit code 13568
log: https://pastebin.com/fgQvEE5J

**Comment by proudhon** [comment]
Ok, I don´t know if this is related to  #4275 but running installers with main user but on a full DE (GNOME on X11) instead of TWM bspwm worked as expected (i defaulted to GNOME with the fresh user, and that's why it was working, my fault)
Logs aren´t showing any info related to this matter though...

**Comment by danieljohnson2** [comment]
@proudhon, Can you *play* already installed WINE games?

All those instances of "Accessing game config while runner wasn't given one" in the log make me suspicious. Maybe something in the config is required, but the config is unused during installation- not even the system or runner config gets in there.

That's an old issue, but the last time I tried to fix it something went wrong and @strycore revert it all. I don't know what broke, but the changes were extensive.

So if you can play WINE games but not install them, maybe I should make another run at this.

**Comment by l0drex** [comment]
I'm using KDE, maybe it only works on Gnome?

I am able to run already installed games. I was also able to install ubisoft connect by running the commands from the script manually

**Comment by proudhon** [comment]
> @proudhon, Can you _play_ already installed WINE games?
> 
> All those instances of "Accessing game config while runner wasn't given one" in the log make me suspicious. Maybe something in the config is required, but the config is unused during installation- not even the system or runner config gets in there.
> 
> That's an old issue, but the last time I tried to fix it something went wrong and @strycore reverted it all. I don't know what broke, but the changes were extensive.
> 
> So if you can play WINE games but not install them, maybe I should make another run at this.

@danieljohnson2 

Yes, I can play already installed games without any problem.
I just realized that I had this very problem months ago and ended up installing all my library in a gnome session.
Totally forgot about this until now.

**Comment by danieljohnson2** [comment]
OK, well, it's a shot in the dark, but try [this branch](https://github.com/lutris/lutris/tree/dj/stab_in_the_dark).

You need not install it, just download it and run the bin/lutris script within. Remember to exit any other Lutris instance first. Try to install a game and see if it is any better this way.

**Comment by proudhon** [comment]
@danieljohnson2 
It just works, installs and plays correctly

**Comment by danieljohnson2** [comment]
Oh, excellent. I'll put something together for the next release.

**Comment by danieljohnson2** [comment]
OK, I've generalized the fix and merged it in. Master branch should now work for you. Please switch to that; I'm deleting my branch.

**Comment by proudhon** [comment]
Thanks a lot! <3

**Comment by danieljohnson2** [comment]
I just hope it will survive the wrath of @strycore. I tried to be much more focused than last time, but you never know...

**Comment by l0drex** [comment]
Unfortunately, the master branch still doesn't work for me. 
I ran `setup.py install` and `bin/lutris`, but still have that empty string error. Did I miss something? Should I create a new issue for this?

<details>
<summary>Logs</summary>

```
2022-10-03 12:15:42,380: Starting Lutris 0.5.11
2022-10-03 12:15:42,490: Using NVIDIA drivers 515.76 for x86_64
2022-10-03 12:15:42,490: GPU: NVIDIA GeForce GTX 1060 6GB
2022-10-03 12:15:42,490: GPU: 10DE:1C03 10DE:1C03 (nvidia drivers)
2022-10-03 12:15:42,653: Startup complete
2022-10-03 12:15:51,878: Getting runner information for wine
2022-10-03 12:15:52,963: All files available
2022-10-03 12:15:52,964: All files are available, continuing install
2022-10-03 12:15:52,968: Skipping caching of /home/l0drex/Downloads/origin/client/OriginSetup.exe, already cached in /home/l0drex/Downloads/origin/client
2022-10-03 12:15:52,971: Creating a win64 prefix in /home/l0drex/.games/origin
2022-10-03 12:15:54,082: win64 Prefix created in /home/l0drex/.games/origin
2022-10-03 12:15:54,189: The game doesn't have an executable
lutris-wrapper: /home/l0drex/.local/share/lutris/runtime/winetricks/winetricks
Started initial process 37254 from /home/l0drex/.local/share/lutris/runtime/winetricks/winetricks --unattended arial
Start monitoring process.
Executing mkdir -p /home/l0drex/.games
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
WINEPREFIX INFO:
Drive C: insgesamt 24
drwxr-xr-x  6 l0drex l0drex 4096  3. Okt 12:10 .
drwxr-xr-x  4 l0drex l0drex 4096  3. Okt 12:10 ..
drwxr-xr-x  3 l0drex l0drex 4096  3. Okt 12:10 ProgramData
drwxr-xr-x  6 l0drex l0drex 4096  3. Okt 12:10 Program Files
drwxr-xr-x  4 l0drex l0drex 4096  3. Okt 12:10 users
drwxr-xr-x 18 l0drex l0drex 4096  3. Okt 12:10 windows

Registry info:
/home/l0drex/.games/origin/system.reg:#arch=win64
/home/l0drex/.games/origin/userdef.reg:#arch=win64
/home/l0drex/.games/origin/user.reg:#arch=win64
------------------------------------------------------
------------------------------------------------------
warning: /home/l0drex/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "" 
------------------------------------------------------
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
2022-10-03 12:15:55,191: Command exited with code 256
None
2022-10-03 12:16:05,538: Cancelling installation of Origin
2022-10-03 12:16:06,708: Shutting down Lutris
```

</details>

**Comment by danieljohnson2** [comment]
@l0drex your log is different. I see "The game doesn't have an executable" in there; that may be the problem. Is the .exe actually there? Is the right .exe specified in the configuration?

If not, file a new issue. It's not the same thing.
