### ISSUE TITLE
Moving games don't work?

### ISSUE THREAD

**Issue by aznlir88** [lutris/lutris#5223]
Hello, just tried to move Rayman Redemption to another location and well... Lutris said it was moved but there is nothing in new place and all data is where it was before. Here you have console output.

```
2024-01-10 10:15:42,157: Moving Rayman Redemption (wine) to /mnt/dane/AZN/lutris_games
(lutris:2678): Gtk-WARNING **: 10:15:44.364: Unpaired gtk_style_context_restore() call
2024-01-10 10:15:44,399: Location /mnt/dane/AZN/lutris_games/rayman-redemption doesn't exist, files already moved?
2024-01-10 10:15:44,507: Finished moving game
2024-01-10 10:15:44,507: Rayman Redemption (wine) moved to /mnt/dane/AZN/lutris_games
```

Maybe it's just me but I would dare to say it does not work.

Using Lutris 0.5.14.

**Comment by aznlir88** [comment]
Just to add, lutris says game is in new directory in game information but it is running it from the old directory. Complete chaos.

**Comment by danieljohnson2** [comment]
I'll look at this when I get a chance, but I'd preemptively ask you to post a more complete log.

Run ``lutris- d`` and try to move a game; there may be more clues in there.

**Comment by danieljohnson2** [comment]
I've done some quick tests, and the move function in 0.5.14 is indeed bugged for Wine games; they move but won't run because it can't restore symlinks (for Proton Wine). The master branch has this fixed, and on master it all worked fine.

I will also suggest you might download the latest master and run the 'bin/lutris' script inside- no need to install- and try to move a game there.  It may work better.

Admittedly, I am not seeing the same symptoms that you describe. But maybe we'll get lucky.

**Comment by aznlir88** [comment]
As of plain 0.5.14 the debug output looks like this:

```
WARNING: radv is not a conformant Vulkan implementation, testing use only.

(lutris:4594): Gtk-WARNING **: 01:02:23.994: Theme parsing error: colors.css:71:44: Invalid number for color value

(lutris:4594): Gtk-WARNING **: 01:02:23.994: Theme parsing error: colors.css:72:44: Invalid number for color value

(lutris:4594): Gtk-WARNING **: 01:02:23.994: Theme parsing error: colors.css:74:53: Invalid number for color value

(lutris:4594): Gtk-WARNING **: 01:02:23.994: Theme parsing error: colors.css:75:53: Invalid number for color value

(lutris:4594): Gtk-WARNING **: 01:02:23.994: Theme parsing error: colors.css:76:56: Invalid number for color value

(lutris:4594): Gtk-WARNING **: 01:02:23.994: Theme parsing error: colors.css:77:65: Invalid number for color value
INFO     2024-01-12 01:02:24,075 [application.do_command_line:436]:Starting Lutris 0.5.14
INFO     2024-01-12 01:02:24,078 [startup.get_drivers:70]:Running AMD Mesa driver 23.0.4 on AMD Radeon HD 7800 Series (pitcairn, LLVM 15.0.7, DRM 3.42, 5.15.0-91-generic) (0x6819)
INFO     2024-01-12 01:02:24,078 [display.display_gpu_info:78]:GPU: 1002:6819 1787:201C (amdgpu drivers)
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
DEBUG    2024-01-12 01:02:24,789 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2024-01-12 01:02:26,473 [lutris.get_missing_game_ids:202]:Checking for missing games
DEBUG    2024-01-12 01:02:31,585 [application.show_window:359]:Showing window EditGameConfigDialog3
INFO     2024-01-12 01:02:43,167 [game.move:958]:Moving Rayman Redemption (wine) to /mnt/dane/AZN/lutris_games/nowe
DEBUG    2024-01-12 01:02:43,167 [game.save:429]:Saving Rayman Redemption (wine) with config ID rayman-redemption-windows-1679573629
DEBUG    2024-01-12 01:02:43,167 [config.save:227]:Saving LutrisConfig(level=game, game_config_id=rayman-redemption-windows-1679573629, runner=wine) config to /home/azn/.config/lutris/games/rayman-redemption-windows-1679573629.yml
DEBUG    2024-01-12 01:02:45,300 [lutris.add_to_path_cache:160]:Adding Rayman Redemption (wine) to path cache
WARNING  2024-01-12 01:02:45,357 [game.move:985]:Can't move /mnt/dane/AZN/lutris_games to one of its children /mnt/dane/AZN/lutris_games/nowe
INFO     2024-01-12 01:02:45,459 [notifications.send_notification:16]:Finished moving game
INFO     2024-01-12 01:02:45,460 [notifications.send_notification:17]:Rayman Redemption (wine) moved to /mnt/dane/AZN/lutris_games/nowe/lutris_games
DEBUG    2024-01-12 01:02:51,619 [application.on_app_window_destroyed:377]:Removed window EditGameConfigDialog3
INFO     2024-01-12 01:02:54,789 [application.do_shutdown:1028]:Shutting down Lutris
```

Tried to move to /mnt/dane/AZN/lutris_games/nowe as after first try Lutris tells me that the game is already in /mnt/dane/AZN/lutris_games that is not true as it is in first directory - yet runs fine. Anyway, needed to add one more folder or moving process did not even start. Now it said it was finished. Not sure why it says in log:
`moved to /mnt/dane/AZN/lutris_games/nowe/lutris_games`
when I wanted to move it to /mnt/dane/AZN/lutris_games/nowe , not /mnt/dane/AZN/lutris_games/nowe/lutris_games.

Anyway, will test you second suggestion tomorrow and let you know.

**Comment by aznlir88** [comment]
Sorry for such rapid another comment, yet tries latest master and same situation, nothing is moved. After each move lutris saves desired location as game's location but that is never true - it is still in the first location and the game runs just fine.

**Comment by danieljohnson2** [comment]
So I am seeing an error in there, which is this:
```
Can't move /mnt/dane/AZN/lutris_games to one of its children /mnt/dane/AZN/lutris_games/nowe
```
I suspect if nothing else we aren't handling this properly.

But first question is - are those the correct paths for where the game was, and where you moved it?

**Comment by danieljohnson2** [comment]
I can repro part of it; you do move a game inside itself, it does partially complete and corrupt the game. I'm working on this now.

**Comment by danieljohnson2** [comment]
OK, I've pushed a commit to mitigate this. If this condition (or a few others) occurs, you will get a warning dialog that will let you just set the location instead of moving the game. This will not change the configuration or move files, you'll have to do that yourself.

If you cancel out, no changes are made.

May not solve your underlying problem, but this should reduce the damage.

**Comment by aznlir88** [comment]
Thanks, currently I have no need to use this functionality yet it's good to know I reported a problem and it is being fixed.

Thanks.

**Comment by danieljohnson2** [comment]
Sure. I believe this particular fix is in 0.5.16 already.

**Comment by audunmg** [comment]
I don't think it's fixed. 

Running 0.5.17 and it doesn't move my game, instead throws an error.

Debug output shows this:

```
(lutris:1938070): Gtk-WARNING **: 23:48:08.123: Theme file for hicolor has no name

(lutris:1938070): Gtk-WARNING **: 23:48:08.123: Theme file for hicolor has no directories

(lutris:1938070): Gtk-WARNING **: 23:48:08.123: Theme file for hicolor has no name

(lutris:1938070): Gtk-WARNING **: 23:48:08.123: Theme file for hicolor has no directories

(lutris:1938070): Gtk-WARNING **: 23:48:08.123: Theme file for hicolor has no name

(lutris:1938070): Gtk-WARNING **: 23:48:08.123: Theme file for hicolor has no directories
INFO     2024-05-24 23:48:08,188 [application.do_command_line:479]:Starting Lutris 0.5.17
INFO     2024-05-24 23:48:08,216 [startup.run_all_checks:120]:Intel UHD Graphics 770 (8086:4680 8086:3020 i915) Driver 24.0.7
INFO     2024-05-24 23:48:08,343 [startup.run_all_checks:120]:NVIDIA RTX A5000 (10de:2231 10de:147e nvidia) Driver 550.78
DEBUG    2024-05-24 23:48:08,439 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-05-24 23:48:08,441 [xrandr._get_vidmodes:18]:Retrieving 35 video modes from XrandR

(lutris:1938070): Gtk-WARNING **: 23:48:08.450: Theme file for hicolor has no name

(lutris:1938070): Gtk-WARNING **: 23:48:08.450: Theme file for hicolor has no directories

(lutris:1938070): Gtk-WARNING **: 23:48:08.450: Theme file for hicolor has no name

(lutris:1938070): Gtk-WARNING **: 23:48:08.450: Theme file for hicolor has no directories

(lutris:1938070): Gtk-WARNING **: 23:48:08.450: Theme file for hicolor has no name

(lutris:1938070): Gtk-WARNING **: 23:48:08.450: Theme file for hicolor has no directories
DEBUG    2024-05-24 23:48:08,469 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-05-24 23:48:08,488 [api.check_stale_runtime_versions:52]:Modified at 2024年05月24日 20時29分53秒, will update after 2024年05月25日 02時29分53秒
DEBUG    2024-05-24 23:48:08,493 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
Gtk-Message: 23:48:08.495: Failed to load module "appmenu-gtk-module"
DEBUG    2024-05-24 23:48:13,019 [application.show_window:394]:Showing window EditGameConfigDialog7
INFO     2024-05-24 23:48:19,320 [game.move:1029]:Moving Starcraft: Brood War (wine) to /home/audunmg/Games/starcraft-working
ERROR    2024-05-24 23:48:19,320 [jobs.target:32]:Error while completing task <bound method MoveDialog._move_game of <dialogs.MoveDialog object at 0x7565316fe8c0 (lutris+gui+dialogs+MoveDialog at 0x59185fc82ba0)>>: <class 'lutris.exceptions.InvalidGameMoveError'> Lutris can't move '/home/audunmg/Games/starcraft' to a location inside of itself, '/home/audunmg/Games/starcraft-working'.
  File "/usr/lib/python3.12/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/gui/dialogs/__init__.py", line 635, in _move_game
    self.new_directory = self.game.move(self.destination, no_signal=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/game.py", line 1035, in move
    raise InvalidGameMoveError(
ERROR    2024-05-24 23:48:19,322 [exception_backstops.error_wrapper:110]:Error handling idle function: Must be string, not InvalidGameMoveError
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/util/jobs.py", line 57, in discarding_result
    function(*args, **kwargs)
  File "/usr/lib/python3.12/site-packages/lutris/gui/dialogs/__init__.py", line 643, in _move_game_cb
    dlg = WarningDialog(message_markup=error, secondary=secondary, parent=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/gui/dialogs/__init__.py", line 266, in __init__
    self.set_markup(message_markup)
TypeError: Must be string, not InvalidGameMoveError
DEBUG    2024-05-24 23:48:24,263 [application.on_app_window_destroyed:419]:Removed window EditGameConfigDialog7
INFO     2024-05-24 23:48:25,369 [application.do_shutdown:1051]:Shutting down Lutris
```

**Comment by danieljohnson2** [comment]
Looks like the previous effort had bugs of its own. The error reporting is bugged, but so is the detection code. It thinks

``~/Games/starcraft`` is inside of ``~/Games/starcraft-working' which is incorrect. It's also not reporting this error incorrectly. Two wrongs fail to make a right, and here we are.

But I've now fixed both issues, I think.

Please download [the latest master branch](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within. No need to install. It should be able to do the move you've asked for here.

**Comment by audunmg** [comment]
Thank you for your quick response, but it seems like it's still a bit strange.

Moving from  /home/audunmg/Games/starcraft-old to  /home/audunmg/Games/starcraft-working results in not moving at all, and this output:
```
2024-05-26 11:07:19,831: Moving Starcraft (wine) to /home/audunmg/Games/starcraft-old
2024-05-26 11:07:19,852: Initial location %s does not exist, files may have already been moved.
2024-05-26 11:07:19,853: error parsing file /home/audunmg/.config/lutris/games/starcraft-1716565447.yml
2024-05-26 11:07:19,874: Finished moving game
2024-05-26 11:07:19,874: Starcraft (wine) moved to /home/audunmg/Games/starcraft-old
2024-05-26 11:07:22,459: The game doesn't have an executable
2024-05-26 11:07:22,465: The game doesn't have an executable
2024-05-26 11:08:12,480: Moving Starcraft (wine) to /home/audunmg/Games/starcraft-working
2024-05-26 11:08:12,526: Finished moving game
2024-05-26 11:08:12,526: Starcraft (wine) moved to /home/audunmg/Games/starcraft-working/starcraft-old
```

The content of the starcraft-1716565447.yml seems a bit short, (but not wrong?):
```
game:
  arch: win32
  exe: /home/audunmg/Games/starcraft-working/starcraft-old/drive_c/Starcraft/StarCraft.exe
  prefix: /home/audunmg/Games/starcraft-working/starcraft-old
  working_dir: /home/audunmg/Games/starcraft-working/starcraft-old/drive_c/Starcraft/
```

**Comment by audunmg** [comment]
Nevermind, my mistake!

The game was moved to /home/audunmg/Games/starcraft-working/starcraft-old, I was just confused by the console output.

Thank you again!

**Comment by musjj** [comment]
Also having this issue. Is a new version with the commit coming out soon? It's been months since the last release cut.

**Comment by danieljohnson2** [comment]
A quick test suggests to me that your bug isn't fixed, @musjj. I'll have a look at it soon.

**Comment by danieljohnson2** [comment]
OK, Lutris would behave pretty badly when setting the initial directory- it would even corrupt the configuration file for the game.

I've added a check so it will just set the game directory in this case.

@musjj, if you'd like to try it, download [the master branch](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within. No need to install! You should be able to set up your game with the latest code.
